In [3]:
'''
Current System:
Question -> FAISS -> Top 5

New System that we would build:
Questions -> BM25 | FAISS -> Top 20  -> RRF -> Final top results
'''

'\nCurrent System:\nQuestion -> FAISS -> Top 5\n\nNew System that we would build:\nQuestions -> BM25 | FAISS -> Top 20  -> RRF -> Final top results\n'

In [4]:
# Install Libraries
!pip install -q \
langchain \
langchain-community \
langchain-huggingface \
langchain-text-splitters \
faiss-cpu \
rank-bm25 \
sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 86.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 98.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 68.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.4/557.4 kB 40.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 7.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [5]:
# Imports
import numpy as np
from pathlib import Path
from rank_bm25 import BM25Okapi
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

/tmp/ipykernel_2108/2836005086.py:5: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
ROOT_DIR = Path("/content/drive/MyDrive/legal_ai/CUAD_v1")
TXT_DIR = ROOT_DIR / "full_contract_txt"
FAISS_DIR = Path("/content/drive/MyDrive/legal_ai/vectorstores/legal_faiss")

print(TXT_DIR.exists())
print(FAISS_DIR.exists())

True
True

In [8]:
#  lets load contracts
from langchain_core.documents import Document

documents = []

for txt_file in TXT_DIR.rglob("*.txt"):

    with open(
        txt_file,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as f:

        text = f.read()

    filename = txt_file.stem

    contract_type = filename.split("_")[-1]

    documents.append(
        Document(
            page_content=text,
            metadata={
                "source": txt_file.name,
                "contract_type": contract_type
            }
        )
    )

print("Documents Loaded:", len(documents))

Documents Loaded: 510

In [9]:
print(documents[0].page_content)

Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. Amendment #3 to the Manufacturing Agreement This Amendment #3 to the Manufacturing Agreement (this "Amendment #3") is made effective as of December 21, 2017 ("Amendment Effective Date"), by and between ADMA BioManufacturing, LLC, a Delaware limited liability company, having a place of business at 5800 Park of Commerce Boulevard NW, Boca Raton, Florida 33487 USA ("ADMA") and Sanofi Pasteur S.A., a company existing and organized under the laws of France ("Sanofi Pasteur"), having its registered head office at 14, espace Henry Vallee, 69007, Lyon, France. WHEREAS, ADMA (as successor-in-interest to Biotest Pharmaceuticals Corporation ("BPC") and Sanofi Pasteur are parties to that certain Manufacturing Agreement, effective September 30, 2011, as previously amended (including by that certain Amendment #2 to the Manufacturing Agreement, effective as of August 1, 2016, by and between BPC and Sanofi Pasteur ("Amendment #2")) (the "Agreement") for the production of Rabies Fraction II Paste (the "Product," as further defined in the Agreement) for Sanofi Pasteur from human plasma containing rabies antibodies; WHEREAS, BPC and Sanofi Pasteur are Parties to that certain Plasma Supply Agreement, effective January 20, 2009, as amended (the "Plasma Supply Agreement"), for the production of human Rabies Hyperimmune Plasma ("Rabies Plasma") by BPC for Sanofi Pasteur to be used in the manufacturing of Rabies Immunoglobulin; WHEREAS, the Rabies Plasma manufactured by BPC under the Plasma Supply Agreement may be transferred to ADMA to be fractionated into Product under the Agreement; WHEREAS, ADMA and Sanofi Pasteur desire to further amend the Agreement in order to memorialize the amendment of certain provisions in the Agreement; NOW, THEREFORE, in consideration of the respective promises contained herein and other valuable consideration, the receipt and sufficiency of which are hereby acknowledged, and intending to be legally bound hereby, the Parties hereto agree as follows: 1. All capitalized terms used and not defined in this Amendment shall have the meaning as set out in the Agreement. 2. The supply terms set forth in Section 1 of Amendment #2 (the "Prior Supply Terms") are hereby deleted in their entirety. In their place, the Parties agree to the following (and Section 2.1 of the Agreement is hereby amended as needed to implement the following): Sanofi Pasteur agrees to purchase and ADMA to manufacture [***] Batches of Product, which Batches will be produced over a period from Q3 2018 to Q3 2019. Attached hereto as Exhibit A is a detailed supply plan provided to ADMA by Sanofi Pasteur (the "Updated Supply Plan") that describes the agreed-upon timing for production of such Batches of Product, which supply plan is made an integral part hereof and shall be binding on the Parties. Prices for such [***] Batches of Product shall be in accordance with Section 3.2 of the Agreement (as amended in Amendment #2).

BPC Initials ___ Sanofi Pasteur Initials ___ 1





Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. The Parties agree to amend the Agreement to impose on ADMA an obligation to supply a minimum of [***] Batches of Product for that period stalling from Q4 2018 up to Q4 2019, as further specified in Exhibit A attached hereto. Should ADMA fail to supply a minimum of [***] Batches of Product (the "Minimum Volume") of Product during the time period as specified in this Amendment #3, ADMA agrees that Sanofi Pasteur shall be entitled to obtain from ADMA as liquidated damages, and not a penalty, amounting to $[***] ([***]) USD. ADMA accepts and declares that the amount of the liquidated damages is a fair and equitable compensation, and not a penalty, for such failure in reaching the volume commitment within the timelines agreed herein and in regard to the value and use of the Source Plasma. In addition to the Minimum Volume of Product to be manufactured by ADMA, should ADMA deliver the Minimum Volume of Product but fail to meet the Updated Supply Plan as provided in Exhibit A as attached hereto and made an integral part hereof, then it is agreed upon by the Parties that ADMA shall pay to Sanofi Pasteur an amount equal to $[***] ([***]) USD for each Batch of Product that is less than the agreed upon quantity in Exhibit A, as liquidated damages, and not as a penalty. The foregoing liquidated damages [***] respect to the [***] within the [***] agreed in this Amendment #3. [***] not be entitled to [***] by this Agreement as a result of [***], including without limitation [***]. Notwithstanding the foregoing, [***], sections 6.1 and 6.2 of the Agreement [***]. 3. Furthermore, should ADMA's compliance status under the FDA Warning Letter be escalated, and if such consequence limits ADMA's ability to supply the Batches of Product as specified in this Amendment #3 and the Updated Supply Plan or in case of failure by ADMA to supply any Batch of Product under this Amendment, Sanofi Pasteur shall be entitled to terminate immediately this Agreement upon written notice to ADMA and Sanofi Pasteur shall not be obligated to provide any additional payments (as outlined in Section 5 below and payments for any of the unproduced or delivered production batches) to ADMA from the date of such termination. In such a case, the remaining Source Plasma shall be immediately returned to Sanofi Pasteur, under ADMA's liability and expenses. Shipment of the Source Plasma to Sanofi Pasteur shall be made in compliance with the transportation conditions as provided in the Quality Agreement (as defined below), to be further amended by the Parties as contemplated in Section 9 below.

BPC Initials ___ Sanofi Pasteur Initials ___ 2





Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. 4. In the event of a non-conformance in the Source Plasma at the time of delivery of the Source plasma at ADMA's place, or in the event of damaged Source Plasma, which non-conformance, damage or loss in the Source Plasma occurred prior to the transfer of risks in the Source Plasma to ADMA as per Section 7 below, it is agreed upon by the Parties that Sanofi Pasteur shall not be responsible, nor liable, to compensate or indemnify ADMA for the loss of business arising from the fact that, in such a case, the Source Plasma will no longer be manufactured by ADMA and consequently Sanofi Pasteur will not pay for the unproduced batch. 5. In consideration for certain quantities of Product that ADMA would have been contractually obligated to supply, and that Sanofi Pasteur would have been contractually obligated to purchase, under the Agreement, but that will now not be supplied and purchased as a result of the Parties' agreement in Section 2 above, Sanofi Pasteur agrees to pay ADMA an amount of seven million (7,000,000 USD) (the "Compensation Fee") in five installments and will be invoiced as follows: (a) [***] USD upon execution of this Amendment #3 (b) [***] USD on March 1, 2018 (c) [***] USD on June 1, 2018 (d) [***] USD on September 1, 2018 (e) [***] USD on December 1, 2018 Such payments shall be made in accordance with Section 3.4 of the Agreement; provided, however, that the initial payment described in Section 5(a) above shall be due no later than December 31,2017. Each invoice shall reference this Amendment 3 and shall be sent at the following address: Sanofi Pasteur SA DSFF Pole de Lyon - Carteret Tri C5-2-01 14 Espace Henry Vallee CS 90119 69361 LYON CEDEX 07 - FRANCE Upon payment of the Compensation Fee, ADMA shall be fully compensated for any kind of prejudice or damages ADMA may suffer arising from or related to the decrease in the quantities of Product Sanofi Pasteur committed to purchase initially from ADMA as per the Prior Supply Terms. ADMA declares that the Compensation Fee is fair and equitable. 6. Upon full payment of the Compensation Fee, each Party, with the intention of binding itself, its Affiliates, shareholders, successors and assigns, hereby releases, remises and forever discharges the other Party, and its Affiliates, employees, directors, shareholders, successors and assigns, from all actions, causes of action, suits, debts, dues, sums of money, accounts, covenants, contracts, controversies, agreements, promises, damages, claims and demands whatsoever, in law, contract or equity, arising directly out of, or relating to the Updated Supply Plan and/or the amount of the Compensation Fee Sanofi agrees to pay to ADMA.

BPC Initials ___ Sanofi Pasteur Initials ___ 3





Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. 7. The Parties further agree to amend Section 6.5 of the Agreement as follows: (a) The liability cap set forth under section 6.5 is hereby amended to adapt to the provisions of this Amendment #3 and is therefore set at "[***]" instead of "[***]". (b) The last sentence of Section 6.5 of the Agreement is hereby deleted and replaced with the following: Unless Section 2.7 applies, and subject to any risk of loss assumed by BPC under the Plasma Agreement (as amended) or that certain [Termination, Settlement and Release Agreement] between BPC and Sanofi Pasteur, [of even date herewith], Sanofi Pasteur assumes all risk of loss for all Source Plasma (the "Sanofi Pasteur Property") while under storage conditions at BPC's warehouse except in case such loss occurs as a result of BPC negligence or willful misconduct, and Sanofi Pasteur hereby waives any and all rights of recovery against ADMA and its Affiliates, and against any of their respective directors, officers, employees, agents or representative, for any loss or damage to the Sanofi Pasteur Property while under storage conditions at BPC's warehouse. At such time that the Source Plasma is delivered to the ADMA loading dock located at 5800 Park of Commerce Blvd NW, Boca Raton, FL 33487, risk of loss for such delivered Source Plasma shall, as between Sanofi Pasteur and ADMA, transfer to ADMA. ADMA agrees to assume the risks of loss to the Sanofi Pasteur Property and shall reimburse Sanofi Pasteur, at the dollar value, the Source Plasma in case of damage or loss. In consideration of the foregoing, Section 6.5 is deleted in its entirety and replaced by the following: 6.5 Limitation of Liability: In no event shall either party be liable to the other party for incidental, indirect, special and consequential or punitive damages, including without limitation any claims for damages based upon lost profits or lost business opportunity. Except for the obligation of indemnity as set forth in Section 6.1 (c) with respect to claims by third parties for personal injury, illness or death (but not including property damage) resulting from the manufacture of the Product by BPC, aggregate damages for which ADMA shall be liable to Sanofi Pasteur hereunder, including without limitation costs of Source Plasma yield loss and/or rejected Batches, shall not exceed [***]. All claims by Sanofi Pasteur for breach or default under this Agreement shall be brought within [***] year after the cause of action comes into existence or otherwise shall be waived. This limitation of liability will not apply for damages that result from the gross negligence or the willful misconduct of a Party.

BPC Initials ___ Sanofi Pasteur Initials ___ 4





Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. Furthermore, unless Section 2.7 applies, and subject to any risk of loss assumed by BPC under the Plasma Agreement (as amended) or that certain [Termination, Settlement and Release Agreement] between BPC and Sanofi Pasteur, [of even date herewith], Sanofi Pasteur assumes all risk of loss for all Source Plasma (the "Sanofi Pasteur Property") while under storage conditions at BPC's warehouse except in case such loss occurs as a result of BPC negligence or willful misconduct, and Sanofi Pasteur hereby waives any and all rights of recovery against ADMA and its Affiliates, and against any of their respective directors, officers, employees, agents or representative, for any loss or damage to the Sanofi Pasteur Property while under storage conditions at BPC's warehouse. At such time that the Source Plasma is delivered to the ADMA loading dock located at 5800 Park of Commerce Blvd NW, Boca Raton, FL 33487, risk of loss for such delivered Source Plasma shall, as between Sanofi Pasteur and ADMA, transfer to ADMA. ADMA agrees to assume the risks of loss to the Sanofi Pasteur Property and shall reimburse Sanofi Pasteur, at the dollar value, the Source Plasma in case of damage or loss. 8. The Parties further agree to amend that certain Quality and Technical Agreement between Sanofi Pasteur and ADMA (as successor to BPC) effective as of September 15, 2015 (the "Quality Agreement") to modify the address where the Source Plasma shall be stocked and the conditions associated therewith, as well as to ensure consistency with the other terms of this Amendment. The Parties shall use best efforts to complete such amendment to the Quality Agreement within 60 days after the Amendment Effective Date. 9. All other terms of the Agreement shall remain in full force and effect except to the extent superseded by the terms of this Amendment #3. IN WITNESS WHEREOF, the parties hereby have caused this Amendment #3 to the Agreement to be executed and the persons signing below warrant that they are duly authorized to sign for and on behalf of their respective Parties. Made in two original copies. Sanofi Pasteur, S.A. By:/s/ Vincent Hingot Name: Vincent Hingot Title: Senior Vice President Industrial Affairs Date: 22 Dec. 2017

ADMA BioManufacturing, LLC By: /s/ Adam Grossman Name: Adam Grossman Title: President & CEO Date: 12-21-2017

BPC Initials ___ Sanofi Pasteur Initials ___ 5





Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. Exhibit A [***] ADMA Initials ___ Sanofi Pasteur Initials ___ A-1

In [10]:
print(documents[10].metadata)
print(documents[10].metadata.items())

{'source': 'AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt', 'contract_type': 'Development Agreement'}
dict_items([('source', 'AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt'), ('contract_type', 'Development Agreement')])

In [11]:
contract_types = []

for doc in documents:
    contract_types.append(
        doc.metadata["contract_type"]
    )

print("Unique Types:", len(set(contract_types)))

for c in sorted(set(contract_types))[:50]:
    print(c)

Unique Types: 370
 Agency Agreement
 Investment Distribution Agreement
 MARKETING AGREEMENT
 Reseller Agreement
 Sales-Purchase Agreement1
 Sales-Purchase Agreement2
 Service Agreement
 Supply Agreement
 WILCOX ENTERPRISES, INC.
1994-EX-10.47-EXCLUSIVE DISTRIBUTOR AGREEMENT
1996-EX-1.1-AGENCY AGREEMENT
1996-EX-10.12-ENDORSEMENT AGREEMENT
1996-EX-10.4-SPONSORSHIP AGREEMENT
1996-EX-10.4-TRANSPORTATION SERVICES AGREEMENT
1997-EX-10.11-SPONSORSHIP AGREEMENT
1997-EX-10.16-SPONSORSHIP AGREEMENT
1997-EX-10.2-10-ENDORSEMENT AGREEMENT
1997-EX-10.28-ENDORSEMENT AGREEMENT
1997-EX-10.46-WEB HOSTING AGREEMENT
1997-EX-10.47-SPONSORSHIP AGREEMENT
1997-EX-4-AFFILIATE AGREEMENT
1997-EX-99-FRANCHISE AGREEMENT
1998-EX-10-FRANCHISE AGREEMENT
1998-EX-10-OUTSOURCING AGREEMENT
1998-EX-10-SPONSORSHIP AGREEMENT
1998-EX-10.13-PROMOTION AGREEMENT
1998-EX-10.14-OUTSOURCING AGREEMENT
1998-EX-10.14-SOFTWARE HOSTING AGREEMENT
1998-EX-10.15-SPONSORSHIP AGREEMENT
1998-EX-10.16-SPONSORSHIP AGREEMENT
1998-EX-10.17-SPONSORSHIP AGREEMENT
1998-EX-10.3-FRANCHISE AGREEMENT
1998-EX-10.3-SOFTWARE LICENSE AND MAINTENANCE AGREEMENT
1998-EX-10.3-TRANSPORTATION CONTRACT
1998-EX-10.30-CONSTRUCTION AND MAINTENANCE AGREEMENT
1998-EX-10.5-STRATEGIC ALLIANCE AGREEMENT
1998-EX-10.6-DISTRIBUTOR AGREEMENT
1999-EX-1-AGENCY AGREEMENT
1999-EX-10-DISTRIBUTOR AGREEMENT
1999-EX-10-ENDORSEMENT AGREEMENT
1999-EX-10-ONLINE HOSTING AGREEMENT
1999-EX-10.(D)-PROMOTION AGREEMENT AND NANTZ COMMUNICATIONS, INC.
1999-EX-10.1-HOSTING AND MANAGEMENT AGREEMENT (1)
1999-EX-10.1-HOSTING AND MANAGEMENT AGREEMENT - Escrow Agreement
1999-EX-10.13-AGENCY AGREEMENT
1999-EX-10.16-SPONSORSHIP AGREEMENT
1999-EX-10.17-OUTSOURCING AGREEMENT
1999-EX-10.17-TECHNICAL INFRASTRUCTURE MAINTENANCE AGREEMENT
1999-EX-10.18-SPONSORSHIP AGREEMENT
1999-EX-10.2-SITE DEVELOPMENT AND HOSTING AGREEMENT

In [12]:
'''our current contract metadata is noisy, and if we build filtering and risk analysis
by this we will get 370 categories which is useless so we will try to optimise the
contract extraction via regular expressions.  '''

# Legal Contract Taxonomy
def extract_contract_type(filename):

    filename = filename.lower()

    contract_patterns = [

        "manufacturing agreement",
        "license agreement",
        "affiliate agreement",
        "consulting agreement",
        "distribution agreement",
        "development agreement",
        "supply agreement",
        "joint venture agreement",
        "strategic alliance agreement",
        "outsourcing agreement",
        "sponsorship agreement",
        "maintenance agreement",
        "service agreement",
        "agency agreement",
        "promotion agreement",
        "hosting agreement",
        "franchise agreement",
        "endorsement agreement",
        "cooperation agreement",
        "transportation agreement"
    ]

    for pattern in contract_patterns:

        if pattern in filename:

            return pattern.title()

    return "Other"

In [13]:
#  lets load contracts
from langchain_core.documents import Document

documents = []

for txt_file in TXT_DIR.rglob("*.txt"):

    with open(
        txt_file,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as f:

        text = f.read()

    filename = txt_file.stem

    contract_type = extract_contract_type(filename)

    documents.append(
        Document(
            page_content=text,
            metadata={
                "source": txt_file.name,
                "contract_type": contract_type
            }
        )
    )

print("Documents Loaded:", len(documents))

Documents Loaded: 510

In [14]:
contract_types = []

for doc in documents:

    contract_types.append(
        doc.metadata["contract_type"]
    )

In [15]:
unique_types = sorted(
    set(contract_types)
)

print("Total Unique Types:", len(unique_types))
print()

for contract_type in unique_types:
    print(contract_type)

Total Unique Types: 21

Affiliate Agreement
Agency Agreement
Consulting Agreement
Cooperation Agreement
Development Agreement
Distribution Agreement
Endorsement Agreement
Franchise Agreement
Hosting Agreement
Joint Venture Agreement
License Agreement
Maintenance Agreement
Manufacturing Agreement
Other
Outsourcing Agreement
Promotion Agreement
Service Agreement
Sponsorship Agreement
Strategic Alliance Agreement
Supply Agreement
Transportation Agreement

In [16]:
from collections import Counter

type_counts = Counter(contract_types)

print("Contract Type Counts")
print("=" * 50)

for contract_type, count in sorted(
    type_counts.items(),
    key=lambda x: x[1],
    reverse=True
):
    print(f"{contract_type:<30} {count}")

Contract Type Counts
==================================================
Other                          150
License Agreement              34
Maintenance Agreement          32
Strategic Alliance Agreement   32
Sponsorship Agreement          30
Development Agreement          28
Endorsement Agreement          24
Supply Agreement               21
Outsourcing Agreement          18
Hosting Agreement              18
Service Agreement              15
Cooperation Agreement          15
Franchise Agreement            15
Manufacturing Agreement        14
Agency Agreement               14
Consulting Agreement           11
Promotion Agreement            11
Affiliate Agreement            10
Joint Venture Agreement        9
Transportation Agreement       6
Distribution Agreement         3

In [17]:
other_examples = []

for doc in documents:

    if doc.metadata["contract_type"] == "Other":

        other_examples.append(
            doc.metadata["source"]
        )

print("Total Others:", len(other_examples))
print()

for file in other_examples[:50]:
    print(file)

Total Others: 150

BERKELEYLIGHTS,INC_06_26_2020-EX-10.12-COLLABORATION AGREEMENT.txt
ARMSTRONGFLOORING,INC_01_07_2019-EX-10.2-INTELLECTUAL PROPERTY AGREEMENT.txt
AULAMERICANUNITTRUST_04_24_2020-EX-99.8.77-SERVICING AGREEMENT.txt
Array BioPharma Inc. - LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT.txt
ASIANDRAGONGROUPINC_08_11_2005-EX-10.5-Reseller Agreement.txt
ANIXABIOSCIENCESINC_06_09_2020-EX-10.1-COLLABORATION AGREEMENT.txt
ACCURAYINC_09_01_2010-EX-10.31-DISTRIBUTOR AGREEMENT.txt
ADIANUTRITION,INC_04_01_2005-EX-10.D2-RESELLER AGREEMENT.txt
AIRSPANNETWORKSINC_04_11_2000-EX-10.5-Distributor Agreement.txt
ABILITYINC_06_15_2020-EX-4.25-SERVICES AGREEMENT.txt
ArmstrongFlooringInc_20190107_8-K_EX-10.2_11471795_EX-10.2_Intellectual Property Agreement.txt
BABCOCK_WILCOXENTERPRISES,INC_08_04_2015-EX-10.17-INTELLECTUAL PROPERTY AGREEMENT between THE BABCOCK _ WILCOX COMPANY and BABCOCK _ WILCOX ENTERPRISES, INC..txt
ATENTOSA_07_06_2020-EX-99.1-JOINT FILING AGREEMENT.txt
CERES,INC_01_25_2012-EX-10.20-Collaboration Agreement.txt
EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.txt
EmbarkComInc_19991008_S-1A_EX-10.10_6487661_EX-10.10_Co-Branding Agreement.txt
ENTERTAINMENTGAMINGASIAINC_02_15_2005-EX-10.5-DISTRIBUTOR AGREEMENT.txt
EdietsComInc_20001030_10QSB_EX-10.4_2606646_EX-10.4_Co-Branding Agreement.txt
EmmisCommunicationsCorp_20191125_8-K_EX-10.6_11906433_EX-10.6_Marketing Agreement.txt
BLACKROCKMUNIHOLDINGSINVESTMENTQUALITYFUND_04_07_2020-EX-99.01-JOINT FILING AGREEMENT.txt
BIOCEPTINC_08_19_2013-EX-10-COLLABORATION AGREEMENT.txt
DYNAMEXINC_06_06_1996-EX-10.4-TRANSPORTATION SERVICES AGREEMENT.txt
DIVERSINETCORP_03_01_2012-EX-4-RESELLER AGREEMENT.txt
EUROPEANMICROHOLDINGSINC_03_06_1998-EX-10.6-DISTRIBUTOR AGREEMENT.txt
CcRealEstateIncomeFundadv_20181205_POS 8C_EX-99.(H)(3)_11447739_EX-99.(H)(3)_Marketing Agreement.txt
CUROGROUPHOLDINGSCORP_05_04_2020-EX-10.3-SERVICING AGREEMENT.txt
ETELOS,INC_03_09_2004-EX-10.8-DISTRIBUTOR AGREEMENT.txt
ENTERPRISEPRODUCTSPARTNERSLP_07_08_1998-EX-10.3-TRANSPORTATION CONTRACT.txt
CerenceInc_20191002_8-K_EX-10.4_11827494_EX-10.4_Intellectual Property Agreement.txt
BLACKBOXSTOCKSINC_08_05_2014-EX-10.1-DISTRIBUTOR AGREEMENT.txt
CARDAX,INC_08_19_2014-EX-10.1-COLLABORATION AGREEMENT.txt
CHAPARRALRESOURCESINC_03_30_2000-EX-10.66-TRANSPORTATION CONTRACT.txt
BravatekSolutionsInc_20170418_8-K_EX-10.1_10205739_EX-10.1_Reseller Agreement.txt
GRANTIERRAENERGYINC_05_07_2012-EX-10.6-TRANSPORTATION CONTRACT.txt
InnerscopeHearingTechnologiesInc_20181109_8-K_EX-10.6_11419704_EX-10.6_Distributor Agreement.txt
GarrettMotionInc_20181001_8-K_EX-2.4_11364532_EX-2.4_Intellectual Property Agreement.txt
GWG HOLDINGS, INC. - ORDERLY MARKETING AGREEMENT.txt
FIDELITYNATIONALINFORMATIONSERVICES,INC_08_05_2009-EX-10.3-INTELLECTUAL PROPERTY AGREEMENT.txt
HealthcareIntegratedTechnologiesInc_20190812_8-K_EX-10.1_11776966_EX-10.1_Reseller Agreement.txt
FEDERATEDGOVERNMENTINCOMESECURITIESINC_04_28_2020-EX-99.SERV AGREE-SERVICES AGREEMENT.txt
FuseMedicalInc_20190321_10-K_EX-10.43_11575454_EX-10.43_Distributor Agreement.txt
GALERATHERAPEUTICS,INC_02_14_2020-EX-99.A-JOINT FILING AGREEMENT.txt
ImpresseCorp_20000322_S-1A_EX-10.11_5199234_EX-10.11_Co-Branding Agreement.txt
ImineCorp_20180725_S-1_EX-10.5_11275970_EX-10.5_Distributor Agreement.txt
FEDERATEDGOVERNMENTINCOMESECURITIESINC_04_28_2020-EX-99.SERV AGREE-SERVICES AGREEMENT_POWEROF.txt
FOUNDATIONMEDICINE,INC_02_02_2015-EX-10.2-Collaboration Agreement.txt
INGEVITYCORP_05_16_2016-EX-10.5-INTELLECTUAL PROPERTY AGREEMENT.txt
InvendaCorp_20000828_S-1A_EX-10.2_2588206_EX-10.2_Co-Branding Agreement.txt
INNOVIVA,INC_08_07_2014-EX-10.1-COLLABORATION AGREEMENT.txt
JINGWEIINTERNATIONALLTD_10_04_2007-EX-10.7-INTELLECTUAL PROPERTY AGREEMENT.txt

In [18]:
#  Using llms to extract contract type
sample_docs = documents[:30]

for i, doc in enumerate(sample_docs):

    print("="*80)
    print(f"DOCUMENT {i+1}")

    print(doc.metadata["source"])

    print(doc.page_content[:500])

================================================================================
DOCUMENT 1
ADMA BioManufacturing, LLC -  Amendment #3 to Manufacturing Agreement .txt
Confidential treatment has been requested with respect to portions of this agreement as indicated by "[***]" and such confidential portions have been deleted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended. Amendment #3 to the Manufacturing Agreement This Amendment #3 to the Manufacturing Agreement (this "Amendment #3") is made effective as of December 21, 2017 ("Amendment Effective Date"), by and between
================================================================================
DOCUMENT 2
ALLIANCEBANCORPINCOFPENNSYLVANIA_10_18_2006-EX-1.2-AGENCY AGREEMENT.txt
Exhibit 1.2

Up to 2,445,223 Shares

(subject to increase to up to 2,812,006 shares in the event of an increase in the pro forma market value of the Company's Common Stock)

Alliance Bancorp, Inc. of Pennsylvania (a federal stock holding company)

Common Stock (par value $.01 per share)

AGENCY AGREEMENT

November ___, 2006

SANDLER O'NEILL & PARTNERS, L.P. 919 Third Avenue, 6  Floor New York, New York 10022

Ladies and Gentlemen:

Greater Delaware Valley Holdings, A Mutual Company, a Pennsylvan
================================================================================
DOCUMENT 3
BELLRINGBRANDS,INC_02_07_2020-EX-10.18-MASTER SUPPLY AGREEMENT.txt
EXHIBIT 10.18

CERTAIN CONFIDENTIAL INFORMATION CONTAINED IN THIS DOCUMENT, MARKED WITH "[***]", HAS BEEN EXCLUDED BECAUSE IT IS NOT MATERIAL AND WOULD BE COMPETITIVELY HARMFUL IF PUBLICLY DISCLOSED.

MASTER SUPPLY AGREEMENT

THIS MASTER SUPPLY AGREEMENT ("Agreement") is made as of 31 October 2019 ("Effective Date") by and between Premier Nutrition Company, LLC, a Delaware limited liability company with its headquarters located at 1222 67th Street, Suite 210, Emeryville, CA 94608 ("Buyer" or "PN
================================================================================
DOCUMENT 4
AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.txt
Exhibit 10.19 JOINT CONTENT LICENSE AGREEMENT This JOINT CONTENT LICENSE AGREEMENT (the "Agreement"), dated February 1, 2018 (the "Effective Date"), is made by and between WPT Enterprises, Inc., a Delaware corporation, with offices located at 1920 Main Street, Suite 1150, Irvine, CA 92614 ("WPT"), and ZYNGA INC., a Delaware corporation with offices located at 699 8th Street, San Francisco CA, 94103 ("Zynga US") and ZYNGA GAME IRELAND LIMITED, a limited company organized under the laws of Ireland
================================================================================
DOCUMENT 5
ArconicRolledProductsCorp_20191217_10-12B_EX-2.7_11923804_EX-2.7_Trademark License Agreement.txt
Exhibit 2.7 FORM OF TRADEMARK LICENSE AGREEMENT THIS TRADEMARK LICENSE AGREEMENT (this "Agreement"), made and entered into as of the [ ] day of [ ], 2020 (the "Effective Date"), by and between ARCONIC INC., a corporation organized under the laws of Delaware ("Licensee") and ARCONIC ROLLED PRODUCTS CORP., a corporation organized under the laws of Delaware ("Licensor"). WHEREAS, Licensor and Licensee entered into a Separation and Distribution Agreement having an effective date of the [ ] day of [
================================================================================
DOCUMENT 6
AzulSa_20170303_F-1A_EX-10.3_9943903_EX-10.3_Maintenance Agreement1.txt
Execution version

Exhibit 10.3

CONFIDENTIAL TREATMENT REQUESTED - REDACTED COPY Confidential Treatment has been requested for portions of this Exhibit. Confidential portions of this Exhibit are designated by [*****]. A complete version of this Exhibit has been filed separately with the Securities and Exchange Commission.

GLOBAL MAINTENANCE AGREEMENT Contract No. DS/CS-3957/14 issue 7

Between

AZUL LINHAS AÉREAS BRASILEIRAS S/A (as Company)

and

AVIONS DE TRANSPORT REGIONAL, G.I.E. (as Repai
================================================================================
DOCUMENT 7
ATMOSENERGYCORP_11_22_2002-EX-10.17-TRANSPORTATION SERVICE AGREEMENT.txt
EXHIBIT 10.17

                        TRANSPORTATION SERVICE AGREEMENT                          UNDER RATE SCHEDULE FTS OR ITS

         THIS AGREEMENT ("Agreement"), entered into on May 20, 1992, is between Arkansas Western Pipeline Company ("Transporter"), an Arkansas corporation, and Associated Natural Gas Company, a division of Arkansas Western Gas Company, ("Shipper");

                                  WITNESSETH:

         WHEREAS, Shipper has requested natural gas for that Transporter t
================================================================================
DOCUMENT 8
AFSALABANCORPINC_08_01_1996-EX-1.1-AGENCY AGREEMENT.txt
Exhibit 1.1

                                1,265,000 Shares                    (subject to increase up to 1,454,750 shares                       in the event of an oversubscription)

                              AFSALA BANCORP, INC.                             (a Delaware corporation)

                                  COMMON STOCK                            ($0.10 Par Value Per Share)

                      Subscription Price: $10.00 Per Share

                                AGENCY AGREEMEN
================================================================================
DOCUMENT 9
ArcaUsTreasuryFund_20200207_N-2_EX-99.K5_11971930_EX-99.K5_Development Agreement.txt
Exhibit 99(k)(5) FORM OF BLOCKCHAIN ADMINISTRATION AND DEVELOPMENT AGREEMENT BETWEEN ARCA U.S. TREASURY FUND AND ARCA CAPITAL MANAGEMENT, LLC This Agreement ("Agreement") is made as of [___], 2020 by and between ARCA U.S. TREASURY FUND, a Delaware statutory trust (the "Fund"), and ARCA CAPITAL MANAGEMENT, LLC, a Delaware limited liability company (the "Blockchain Administrator"). WHEREAS, the Fund is a closed-end management investment fund that has registered as an investment company under the I
================================================================================
DOCUMENT 10
AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.34_11788308_EX-10.34_Sponsorship Agreement.txt
Exhibit 10.34 EVENT SPONSORSHIP AGREEMENT This Event Sponsorship Agreement ("Agreement") is made and effective as of February 1, 2019 (the "Effective Date"), by and between Newegg Inc. ("Newegg"), a Delaware corporation, and Allied Esports International, Inc., a Nevada corporation ("Allied"). Newegg and Allied are hereinafter referred to jointly as the "Parties" and each as a "Party." BACKGROUND A. Newegg, an online retailer of items including computer hardware and consumer electronics, is in th
================================================================================
DOCUMENT 11
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt
Exhibit 10.3

[***] Certain information in this document has been excluded pursuant to Regulation S-K, Item 601(b)(10). Such excluded information is not material and would likely cause competitive harm to the registrant if publicly disclosed.

Execution Copy

LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT

DATED AS OF FEBRUARY 4, 2020

BY AND BETWEEN

XENCOR, INC.

AND

AIMMUNE THERAPEUTICS, INC.

Source: AIMMUNE THERAPEUTICS, INC., 8-K, 2/5/2020





TABLE OF CONTENTS Page ARTICLE 1 Defin
================================================================================
DOCUMENT 12
AgapeAtpCorp_20191202_10-KA_EX-10.1_11911128_EX-10.1_Supply Agreement.txt
ODM - SUPPLY AGREEMENT BETWEEN: ORGANIC PREPARATIONS INC. 2nd Floor, Transpacific Haus Lini Highway, Port Vila. Vanuatu "the Manufacturer" -- AND -- AGAPE ATP INTERNATIONAL HOLDING LIMITED Unit 05, 4F, Energy Plaza No. 92, Granville Road Tsim Sha Tsui East Kowloon, Hong Kong "the Customer"

Source: AGAPE ATP CORP, 10-K/A, 12/2/2019





ODM SUPPLY AGREEMENT THIS AGREEMENT is made on the 15t h day of January 2018. BETWEEN: ORGANIC PREPARATIONS INC. 2nd Floor, Transpacific Haus Lini Highway, Port
================================================================================
DOCUMENT 13
ADUROBIOTECH,INC_06_02_2020-EX-10.7-CONSULTING AGREEMENT.txt
Exhibit 10.7

CONSULTING AGREEMENT

Aduro Biotech, Inc., with a place of business at 740 Heinz Avenue, Berkeley, CA 94710 ("Aduro") and IREYA B.V having an address at Staalwijkstraat 16, 2313 XR Leiden, the Netherlands, represented by Andrea van Elsas, ("Consultant") agree to all terms and conditions of this Consulting Agreement ("Agreement") dated June 1, 2020, effective as of July 1, 2020 ("Effective Date").

1. Services. At the request and direction of Aduro and the agreement of Consultant, C
================================================================================
DOCUMENT 14
BERKELEYLIGHTS,INC_06_26_2020-EX-10.12-COLLABORATION AGREEMENT.txt
Exhibit 10.12

[***] Certain information in this document has been excluded pursuant to Regulation S-K, Item 601(b)(10). Such excluded information is not material and would likely cause competitive harm to the registrant if publicly disclosed.

Execution Version

COLLABORATION AGREEMENT

This COLLABORATION AGREEMENT (this "Agreement"), effective as of September 13th, 2019 ("Effective Date"), is between Ginkgo Bioworks, Inc., a Delaware corporation with offices located at 27 Drydock Avenue, 8th f
================================================================================
DOCUMENT 15
ARMSTRONGFLOORING,INC_01_07_2019-EX-10.2-INTELLECTUAL PROPERTY AGREEMENT.txt
Exhibit 10.2

Execution Version

INTELLECTUAL PROPERTY AGREEMENT

This INTELLECTUAL PROPERTY AGREEMENT (this "Agreement"), dated as of December 31, 2018 (the "Effective Date") is entered into by and between Armstrong Flooring, Inc., a Delaware corporation ("Seller") and AFI Licensing LLC, a Delaware limited liability company ("Licensing" and together with Seller, "Arizona") and AHF Holding, Inc. (formerly known as Tarzan HoldCo, Inc.), a Delaware corporation ("Buyer") and Armstrong Hardwood Floo
================================================================================
DOCUMENT 16
AULAMERICANUNITTRUST_04_24_2020-EX-99.8.77-SERVICING AGREEMENT.txt
Exhibit 8.77 SERVICING AGREEMENT NATIONWIDE MUTUAL FUNDS Agreement, made as of this day of , 20 between Nationwide Fund Management LLC ("Nationwide"), on behalf of Nationwide Mutual Funds or its surviving entity ("the Trust"), and American United Life Insurance Company, and OneAmerica Securities, Inc., a registered Broker Dealer (collectively referred to as "Servicing Agent," "you" or "your"), whereby you agree to provide certain administrative support services to your customers who may from tim
================================================================================
DOCUMENT 17
Array BioPharma Inc. - LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT.txt
[ * ] = Certain confidential information contained in this document, marked by brackets, has been omitted and filed separately with the Securities and Exchange Commission pursuant to Rule 24b-2 of the Securities Exchange Act of 1934, as amended.

CONFIDENTIAL

EXECUTION VERSION

LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT

THIS LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT (this "Agreement") dated as of May 31, 2017 (the "Effective Date"), is made and entered into by and between
================================================================================
DOCUMENT 18
ADUROBIOTECH,INC_06_02_2020-EX-10.7-CONSULTING AGREEMENT(1).txt
Exhibit 10.7

CONSULTING AGREEMENT

Aduro Biotech, Inc., with a place of business at 740 Heinz Avenue, Berkeley, CA 94710 ("Aduro") and IREYA B.V having an address at Staalwijkstraat 16, 2313 XR Leiden, the Netherlands, represented by Andrea van Elsas, ("Consultant") agree to all terms and conditions of this Consulting Agreement ("Agreement") dated June 1, 2020, effective as of July 1, 2020 ("Effective Date").

1. Services. At the request and direction of Aduro and the agreement of Consultant, C
================================================================================
DOCUMENT 19
ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT.txt
EXHIBIT 10.13

                             JOINT VENTURE AGREEMENT

Collectible Concepts Group, Inc. ("CCGI") and Pivotal Self Service Tech, Inc. ("PVSS"), (the "Parties" or "Joint Venturers" if referred to collectively, or the "Party" or Joint Venturer" if referred to singularly), by this Agreement associate themselves as business associates, and not as partners, in the formation of a joint venture (the "Joint Venture"), for the purpose of engaging generally in the business provided for by ter
================================================================================
DOCUMENT 20
ASIANDRAGONGROUPINC_08_11_2005-EX-10.5-Reseller Agreement.txt
Exhibit 10.5

Reseller Agreement

This Agreement is made and entered into by and between 695014 B.C. Ltd. dba Galaxy Telecom, having a principal office at 200 - 375 Water Street, Vancouver, British Columbia V6B 5C6 Canada ("Galaxy") and Galaxy Telnet SRL, having a principal office at Aleea Malinului, Nr. 11, Bl. D, Scara C, Apt. 43, Constanta, Judetul Constanta, Romania ("Telnet") as of the 1s t day of June, 2004.

WHEREAS: Galaxy is a wholesale provider of Voice over Internet Protocol ("VoIP")
================================================================================
DOCUMENT 21
ASHWORTHINC_01_29_1999-EX-10.(D)-PROMOTION AGREEMENT AND NANTZ COMMUNICATIONS, INC..txt
EXHIBIT 10(d)

PROMOTION AGREEMENT                        ASHWORTH, INC., JAMES W. NANTZ III                          AND NANTZ COMMUNICATIONS, INC.                                               THIS AGREEMENT is entered into by and among ASHWORTH, INC. (The "Company" or "Ashworth"), JAMES W. NANTZ III ("Nantz") and NANTZ COMMUNICATIONS, INC. ("Nantz Communications"), effective as of June 1, 1998.

WHEREAS, the Company desires to retain Nantz Communications and Nantz to provide certain promotion
================================================================================
DOCUMENT 22
ANIXABIOSCIENCESINC_06_09_2020-EX-10.1-COLLABORATION AGREEMENT.txt
Exhibit 10.1

Redactions with respect to certain portions hereof denoted with "***"

COLLABORATION AGREEMENT

This Collaboration Agreement (the "Agreement") is made as of April 14th, 2020 (the "Effective Date") by and between Anixa Biosciences, Inc., a Delaware corporation, located at 3150 Almaden Expressway, Suite 250, San Jose, CA 95118, U.S.A. ("Anixa"), and OntoChem GmbH, a German limited liability company, located at Blücherstr. 24, D-06120 Halle (Saale), Germany ("OntoChem"). Anixa and Ont
================================================================================
DOCUMENT 23
ASPIRITYHOLDINGSLLC_05_07_2012-EX-10.6-OUTSOURCING AGREEMENT.txt
Exhibit 10.6

      OUTSOURCING AGREEMENT        dated as of , 2012        TWIN CITIES POWER HOLDINGS, LLC        and        REDWATER LLC

      $50,000,000.00        Renewable Unsecured Subordinated Notes





     TABLE OF CONTENTS                                                                                                               ARTICLE I DEFINITIONS    1            Section 1.01 Defined Terms    1





Section 1.02 Accounting Terms    4            ARTICLE II APPOINTMENT OF THE AGENT
================================================================================
DOCUMENT 24
ATHENSBANCSHARESCORP_11_02_2009-EX-1.2-AGENCY AGREEMENT , 2009.txt
Exhibit 1.2

ATHENS BANCSHARES CORPORATION  up to    Shares  (subject to increase up to    shares)  COMMON SHARES  ($.01 Par Value)  Subscription Price $10.00 Per Share  AGENCY AGREEMENT   , 2009

Keefe, Bruyette & Woods, Inc.  Investment Banking  10 South Wacker Drive, Suite 3400  Chicago, Illinois 60606

Ladies and Gentlemen:

Athens Bancshares Corporation, a Tennessee corporation (the "Company"), and Athens Federal Community Bank, a federal savings bank located  in Athens, Tennessee (the "Ban
================================================================================
DOCUMENT 25
BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.txt
Exhibit 10.1 [***] = Certain confidential information contained in this document, marked by brackets, has been omitted because it is both (i) not material and (ii) would likely be competitively harmful if publicly disclosed.

Miltenyi Biotec-Bellicum Supply Agreement (Execution Copy March 27, 2019)

SUPPLY AGREEMENT

(MB Global Contract Number MBGCR 19001)

This Supply Agreement (this "Agreement") is made and entered into, effective as of March 27, 2019 (the "Effective Date"), by and between Mil
================================================================================
DOCUMENT 26
ACCURAYINC_09_01_2010-EX-10.31-DISTRIBUTOR AGREEMENT.txt
Exhibit 10.31    PURSUANT TO 17 C.F.R. § 240.24B-2, CONFIDENTIAL INFORMATION (INDICATED BY {*****}) HAS BEEN OMITTED FROM THIS  DOCUMENT AND HAS BEEN FILED SEPARATELY WITH THE SECURITIES AND EXCHANGE COMMISSION PURSUANT TO A  CONFIDENTIAL TREATMENT APPLICATION FILED WITH THE COMMISSION     ACCURAY INCORPORATED  MULTIPLE LINAC AND MULTI-MODALITY   DISTRIBUTOR AGREEMENT     This Multiple LINAC and Multi-Modality Distributor Agreement ("Agreement") is entered into by and between ACCURAY  INCORPORAT
================================================================================
DOCUMENT 27
ADIANUTRITION,INC_04_01_2005-EX-10.D2-RESELLER AGREEMENT.txt
Exhibit 10d-2

                               RESELLER AGREEMENT

                                 BY AND BETWEEN

                                PIVX CORPORATION

                                       AND

                               DETTO TECHNOLOGIES

This Reseller Agreement is entered as of this ___ day of _________, 2004 ("Effective Date") by and between PivX Corporation, a California corporation, having its principal place of business at 23 Corporate Plaza Drive, Newport Beach, Califo
================================================================================
DOCUMENT 28
ADAPTIMMUNETHERAPEUTICSPLC_04_06_2017-EX-10.11-STRATEGIC ALLIANCE AGREEMENT.txt
Exhibit 10.11   ***Certain portions of this exhibit have been omitted based on a request for confidential treatment pursuant to Rule 24b-2 under the Securities Exchange Act of 1934, as amended. The omitted portions have been filed separately with the Securities and Exchange Commission.   STRATEGIC ALLIANCE AGREEMENT     This Strategic Collaboration Agreement ("Agreement"), effective as of the 23rd day of  September, 2016 ("Effective Date"), is entered into by and between The University of Texas
================================================================================
DOCUMENT 29
AMERICASSHOPPINGMALLINC_12_10_1999-EX-10.2-SITE DEVELOPMENT AND HOSTING AGREEMENT.txt
EXHIBIT 10.2

                    SITE DEVELOPMENT AND HOSTING AGREEMENT

                  This SITE DEVELOPMENT AND HOSTING AGREEMENT (the "Agreement") dated as of August 9, 1999 is made between Hanover Direct, Inc. ("HDI"), a New Jersey Corporation, located at 1500 Harbor Boulevard, Weehawken, NJ 07087, and The Deerskin Companies, Inc. (the "Company"), a Nevada corporation, located at 2500 Arrowhead Drive, Carson City, NV 89706. Each of the parties hereto shall be referred to as a "Party".


================================================================================
DOCUMENT 30
AIRSPANNETWORKSINC_04_11_2000-EX-10.5-Distributor Agreement.txt
Exhibit 10.5

Note: Portions of this exhibit indicated by"[*]" are subject to a confidential treatment request, and have been omitted from this exhibit. Complete, unredacted copies of this exhibit have been filed with the Securities and Exchange Commission as part of this Company's confidential treatment request.

Distributor Agreement                              ---------------------


In [19]:
sample_docs = documents[:30]

In [20]:
# Prompt classify
from langchain_core.prompts import ChatPromptTemplate

classification_prompt = ChatPromptTemplate.from_template(
"""
You are a legal contract classification expert.

Your task is to classify the contract into EXACTLY ONE category from the list below.

ALLOWED CATEGORIES:

- Manufacturing Agreement
- License Agreement
- Affiliate Agreement
- Agency Agreement
- Consulting Agreement
- Distribution Agreement
- Development Agreement
- Supply Agreement
- Joint Venture Agreement
- Strategic Alliance Agreement
- Outsourcing Agreement
- Sponsorship Agreement
- Maintenance Agreement
- Service Agreement
- Promotion Agreement
- Hosting Agreement
- Franchise Agreement
- Endorsement Agreement
- Cooperation Agreement
- Transportation Agreement
- Collaboration Agreement
- Intellectual Property Agreement
- Marketing Agreement
- Reseller Agreement
- Servicing Agreement
- Other

RULES:

1. Return ONLY one category.
2. Do NOT explain your answer.
3. Do NOT generate sentences.
4. If multiple categories appear, choose the PRIMARY purpose of the agreement.
5. If none apply, return "Other".

CONTRACT:

{contract_text}

CATEGORY:
"""
)

In [21]:
import os
os.environ["OPENAI_API_KEY"] ="bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tLz9BY3Rpb249Q2FsbFdpdGhCZWFyZXJUb2tlbiZYLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFTSUFYNjZWV1o0S1ZXWFY2MklJJTJGMjAyNjA2MjElMkZldS1ub3J0aC0xJTJGYmVkcm9jayUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjIxVDEyMTY1OVomWC1BbXotRXhwaXJlcz00MzIwMCZYLUFtei1TZWN1cml0eS1Ub2tlbj1JUW9KYjNKcFoybHVYMlZqRUNRYUNtVjFMVzV2Y25Sb0xURWlSekJGQWlCT3JPZFp3RXllbHE4emVOY0pxNmpaajQ2eG1MVGpYUkNUbm5URkg4dlhuUUloQU1OVnc4Qzk0cWU2VndDTiUyRmsyJTJCNlRodFZzekFKYzBzY0k3eVBwS2lSWmVtS3JJRENPMyUyRiUyRiUyRiUyRiUyRiUyRiUyRiUyRiUyRiUyRndFUUFCb01OVFEzTlRFNU5qUTNOVEE1SWd4SENBZ3NuJTJCQlRVeDdaQm5FcWhnUGJCZVolMkI0cFVTY0NSQ0FRblVmR0llWHV2a3hlR0Jmbk9UVzAlMkJLMHV6OFRVJTJCeGdGYSUyQnVta2U3UUUxV3IxTU5GJTJGZTdaZ3JxMllySzlyeFElMkY5R0Fyc2hxTTUlMkJXQjZJcmRzTmVXbG15ZkZzZnVyYWk4ZjhBOSUyQktEUEdrR1o5MEk5cHFrU09veWtzWVZqSWU1d0VKNTJFOVZzUXQ5SVRUdlVlYk9LUHM1NU9DMTczNXZtY2VaWkpWNndOOFlaR0xVeHB1OHpzNnVCd2R2eklUVFNRdHN3eUx1eWRCOXYxcTV3cU51TWxrUW02SlQ1MVhwckJycFZNQTJkZTFYWVFhNzY4RHVWNG5iYU81ZXRaWUFvJTJCbG1MdXJwQzFxa1h2dGdadVBxMm1pZmVKcyUyRmxMeHROcldrJTJCOThVJTJCNnRscFFXWVBIQ3FIOEZYOWJ3JTJGTXk1eUF0N3A3VldsbGFGZmV0VyUyRkZvTjF2eGo4ZG05ZjJKdjRrV0VHR3ZkdFVNRlpscncxQ1IlMkJWN2VxUkxFdWRoMXdsYXQ1RGJ3THRyTExOM2U2aGJtd2UyeDRjdGxHYkdaTVlvTFlXNGZ5UzhjOUNobVFYJTJCTmVrOEJGSDM3MmRxMEpkRFBEaVFBUjdYMG55VnNTa2JNMzZBNUZNVmhtNDMwdk1RZ0N1NlJJTFlsR0xHVDZQdVA2NkhkRHpEWXdzNnpmMFFZNjNnTGpwTFNFWTBCUGQwdndUdGJLdUFvJTJCMzVlT2FmSmZBU1hJMkt6ZElZaWhXJTJGdmVGbmJXZlljdXlIN3VKbkhwNSUyQkptVTdDYVl6OSUyRnZFcU9iWGtEJTJGek4wME5iWFF2ekZTdG84a041cE82dWh6WlBJNm02JTJGSk9aS1RFMHJFMlJFRk9paUs5SnJWNWxUeG9admFlalBqaFZuaERjTnZERlR4TVpQbDFrUmo5QmoyOERDblNsMGZ5NWtib2dlNGxPTmV4c0FzVTRIZklid1VoaDM5ZUJCTDFMeENjcHRFdWVxTzZxQzVjb3NobmVMS0NKMlNhSDJXNCUyRjdhTjRXcVZES2tqaUgzNlB0am5wdHB4cm5iVzFDN0M0TWc2anZ5aFpXQnlJSFQxRmdZTE5YRUJZdlFPbmNTSTQ1Y0txWUdBUjY3QkxrYTNDdDdPZUFKOGVXRSUyQnFKSlpnOFIlMkIyVm9xSmU3Z1N0OUp6TnU4eFBUcGNKSnhrWFpVcTV1VTJGVjNmQ3I3NkZDbU0lMkJWQW9IdGJsc0xabzY1NTNYSmtFcXVLYnl1aFBEcUFkajY2WkJxaFhpdWRqZGIwUk1MTzYlMkZMNGNzOWYzdm1uejJuVXolMkYlMkY0ZWhhbDFWeGclM0QlM0QmWC1BbXotU2lnbmF0dXJlPWNiMTg4MWM0ZWUwYjc1MjQ3MTdjODc3OWNkNzQ1NzUxYmIzOTM4MzVmZWIzMmU1YWI4ZjAwZTRmYmNhZTlhODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JlZlcnNpb249MQ=="
os.environ["OPENAI_BASE_URL"]= "https://bedrock-mantle.eu-north-1.api.aws/v1"

In [22]:
!pip install langchain-openai
from openai import OpenAI
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="openai.gpt-oss-120b",
    temperature=0
)

Collecting langchain-openai
  Downloading langchain_openai-1.3.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.7 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (1.4.8)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.41.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.13.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.8.12)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.16.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.15.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.34.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=2.26.0->langchain-openai) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.26.0->langchain-openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.7->langchain-openai) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-openai) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-openai) (1.0.0)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-openai) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-openai) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->tiktoken<1.0.0,>=0.7.0->langchain-openai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests->tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.5.0)
Downloading langchain_openai-1.3.2-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 kB 11.6 MB/s eta 0:00:00
Installing collected packages: langchain-openai
Successfully installed langchain-openai-1.3.2

In [23]:
response = llm.invoke("What is a Black Hole?")
print(response.content[:100])

**A black hole is a region of space where gravity is so strong that nothing—not even light—can escap

In [24]:
def classify_contract(contract_text):

    chain = classification_prompt | llm

    result = chain.invoke(
        {
            "contract_text": contract_text[:2000]
        }
    )

    return result.content.strip()

In [25]:
for doc in sample_docs:

    prediction = classify_contract(
        doc.page_content
    )

    print()
    print(doc.metadata["source"])
    print("Predicted:", prediction)

ADMA BioManufacturing, LLC -  Amendment #3 to Manufacturing Agreement .txt
Predicted: Manufacturing Agreement

ALLIANCEBANCORPINCOFPENNSYLVANIA_10_18_2006-EX-1.2-AGENCY AGREEMENT.txt
Predicted: Agency Agreement

BELLRINGBRANDS,INC_02_07_2020-EX-10.18-MASTER SUPPLY AGREEMENT.txt
Predicted: Supply Agreement

AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.19_11788293_EX-10.19_Content License Agreement.txt
Predicted: License Agreement

ArconicRolledProductsCorp_20191217_10-12B_EX-2.7_11923804_EX-2.7_Trademark License Agreement.txt
Predicted: License Agreement

AzulSa_20170303_F-1A_EX-10.3_9943903_EX-10.3_Maintenance Agreement1.txt
Predicted: Maintenance Agreement

ATMOSENERGYCORP_11_22_2002-EX-10.17-TRANSPORTATION SERVICE AGREEMENT.txt
Predicted: Transportation Agreement

AFSALABANCORPINC_08_01_1996-EX-1.1-AGENCY AGREEMENT.txt
Predicted: Agency Agreement

ArcaUsTreasuryFund_20200207_N-2_EX-99.K5_11971930_EX-99.K5_Development Agreement.txt
Predicted: Development Agreement

AlliedEsportsEntertainmentInc_20190815_8-K_EX-10.34_11788308_EX-10.34_Sponsorship Agreement.txt
Predicted: Sponsorship Agreement

AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt
Predicted: License Agreement

AgapeAtpCorp_20191202_10-KA_EX-10.1_11911128_EX-10.1_Supply Agreement.txt
Predicted: Supply Agreement

ADUROBIOTECH,INC_06_02_2020-EX-10.7-CONSULTING AGREEMENT.txt
Predicted: Consulting Agreement

BERKELEYLIGHTS,INC_06_26_2020-EX-10.12-COLLABORATION AGREEMENT.txt
Predicted: Collaboration Agreement

ARMSTRONGFLOORING,INC_01_07_2019-EX-10.2-INTELLECTUAL PROPERTY AGREEMENT.txt
Predicted: Intellectual Property Agreement

AULAMERICANUNITTRUST_04_24_2020-EX-99.8.77-SERVICING AGREEMENT.txt
Predicted: Servicing Agreement

Array BioPharma Inc. - LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT.txt
Predicted: License Agreement

ADUROBIOTECH,INC_06_02_2020-EX-10.7-CONSULTING AGREEMENT(1).txt
Predicted: Consulting Agreement

ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT.txt
Predicted: Joint Venture Agreement

ASIANDRAGONGROUPINC_08_11_2005-EX-10.5-Reseller Agreement.txt
Predicted: Reseller Agreement

ASHWORTHINC_01_29_1999-EX-10.(D)-PROMOTION AGREEMENT AND NANTZ COMMUNICATIONS, INC..txt
Predicted: Promotion Agreement

ANIXABIOSCIENCESINC_06_09_2020-EX-10.1-COLLABORATION AGREEMENT.txt
Predicted: Collaboration Agreement

ASPIRITYHOLDINGSLLC_05_07_2012-EX-10.6-OUTSOURCING AGREEMENT.txt
Predicted: Outsourcing Agreement

ATHENSBANCSHARESCORP_11_02_2009-EX-1.2-AGENCY AGREEMENT , 2009.txt
Predicted: Agency Agreement

BELLICUMPHARMACEUTICALS,INC_05_07_2019-EX-10.1-Supply Agreement.txt
Predicted: Supply Agreement

ACCURAYINC_09_01_2010-EX-10.31-DISTRIBUTOR AGREEMENT.txt
Predicted: Distribution Agreement

ADIANUTRITION,INC_04_01_2005-EX-10.D2-RESELLER AGREEMENT.txt
Predicted: Reseller Agreement

ADAPTIMMUNETHERAPEUTICSPLC_04_06_2017-EX-10.11-STRATEGIC ALLIANCE AGREEMENT.txt
Predicted: Strategic Alliance Agreement

AMERICASSHOPPINGMALLINC_12_10_1999-EX-10.2-SITE DEVELOPMENT AND HOSTING AGREEMENT.txt
Predicted: Hosting Agreement

AIRSPANNETWORKSINC_04_11_2000-EX-10.5-Distributor Agreement.txt
Predicted: Distribution Agreement

In [26]:
# metadata base
records = []

for doc in documents:

    prediction = classify_contract(
        doc.page_content[:1200]
    )

    records.append({
        "source": doc.metadata["source"],
        "contract_type": prediction
    })

In [27]:
import pandas as pd

contract_metadata = pd.DataFrame(records)

contract_metadata.head(10)

                                              source             contract_type
0  ADMA BioManufacturing, LLC -  Amendment #3 to ...   Manufacturing Agreement
1  ALLIANCEBANCORPINCOFPENNSYLVANIA_10_18_2006-EX...          Agency Agreement
2  BELLRINGBRANDS,INC_02_07_2020-EX-10.18-MASTER ...          Supply Agreement
3  AlliedEsportsEntertainmentInc_20190815_8-K_EX-...         License Agreement
4  ArconicRolledProductsCorp_20191217_10-12B_EX-2...         License Agreement
5  AzulSa_20170303_F-1A_EX-10.3_9943903_EX-10.3_M...     Maintenance Agreement
6  ATMOSENERGYCORP_11_22_2002-EX-10.17-TRANSPORTA...  Transportation Agreement
7  AFSALABANCORPINC_08_01_1996-EX-1.1-AGENCY AGRE...          Agency Agreement
8  ArcaUsTreasuryFund_20200207_N-2_EX-99.K5_11971...     Development Agreement
9  AlliedEsportsEntertainmentInc_20190815_8-K_EX-...     Sponsorship Agreement

In [28]:
from pathlib import Path

METADATA_DIR = Path(
    "/content/drive/MyDrive/legal_ai/metadata"
)

METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [29]:
contract_metadata.to_csv(
    METADATA_DIR / "contract_type_mapping.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [30]:
from tqdm import tqdm
records = []

for doc in tqdm(documents):

    prediction = classify_contract(
        doc.page_content[:1200]
    )

    records.append({
        "source": doc.metadata["source"],
        "contract_type": prediction
    })

100%|██████████| 510/510 [05:40<00:00,  1.50it/s]

In [31]:
import pandas as pd

contract_metadata = pd.DataFrame(records)

print(contract_metadata.shape)

contract_metadata.head()

(510, 2)

                                              source            contract_type
0  ADMA BioManufacturing, LLC -  Amendment #3 to ...  Manufacturing Agreement
1  ALLIANCEBANCORPINCOFPENNSYLVANIA_10_18_2006-EX...         Agency Agreement
2  BELLRINGBRANDS,INC_02_07_2020-EX-10.18-MASTER ...         Supply Agreement
3  AlliedEsportsEntertainmentInc_20190815_8-K_EX-...        License Agreement
4  ArconicRolledProductsCorp_20191217_10-12B_EX-2...        License Agreement

In [32]:
type_counts = (
    contract_metadata["contract_type"]
    .value_counts()
)

print(type_counts)

contract_type
License Agreement                  53
Distribution Agreement             37
Strategic Alliance Agreement       33
Sponsorship Agreement              31
Endorsement Agreement              25
Maintenance Agreement              24
Development Agreement              22
Service Agreement                  21
Marketing Agreement                21
Supply Agreement                   19
Outsourcing Agreement              19
Cooperation Agreement              19
Manufacturing Agreement            18
Other                              18
Intellectual Property Agreement    17
Agency Agreement                   17
Collaboration Agreement            15
Franchise Agreement                15
Consulting Agreement               14
Transportation Agreement           13
Hosting Agreement                  13
Reseller Agreement                 12
Promotion Agreement                11
Joint Venture Agreement            10
Affiliate Agreement                10
Servicing Agreement                 3
Name: count, dtype: int64

In [33]:
from pathlib import Path
PROJECT_DIR = Path("/content/drive/MyDrive/legal_ai")
METADATA_DIR = PROJECT_DIR / "metadata"

METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [34]:
contract_metadata.to_csv(
    METADATA_DIR / "contract_type_mapping.csv",
    index=False
)

print("Metadata Saved")

Metadata Saved

In [35]:
contract_type_lookup = dict(
    zip(
        contract_metadata["source"],
        contract_metadata["contract_type"]
    )
)

In [36]:
for doc in documents:

    source = doc.metadata["source"]

    doc.metadata["contract_type"] = (
        contract_type_lookup[source]
    )

In [37]:
print(documents[150].metadata)

{'source': 'ImperialGardenResortInc_20161028_DRS (on F-1)_EX-10.13_9963189_EX-10.13_Outsourcing Agreement.txt', 'contract_type': 'Outsourcing Agreement'}

In [38]:
import pickle

with open(
    METADATA_DIR / "documents_with_metadata.pkl",
    "wb"
) as f:

    pickle.dump(documents, f)

In [39]:
METADATA_DIR = Path(
    "/content/drive/MyDrive/legal_ai/metadata"
)

for file in METADATA_DIR.iterdir():
    print(file.name)

contract_type_mapping.csv
documents_with_metadata.pkl

Chunking and Embeddings

In [40]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = text_splitter.split_documents(
    documents
)

print("Total Chunks:", len(chunks))

Total Chunks: 39025

In [41]:
print(chunks[0].metadata)

{'source': 'ADMA BioManufacturing, LLC -  Amendment #3 to Manufacturing Agreement .txt', 'contract_type': 'Manufacturing Agreement'}

In [42]:
chunk_lengths = [
    len(chunk.page_content)
    for chunk in chunks
]

print("Min:", min(chunk_lengths))
print("Max:", max(chunk_lengths))
print("Average:",
    round(sum(chunk_lengths)/len(chunk_lengths),2)
)

Min: 1
Max: 1000
Average: 762.97

In [43]:
small_chunks = [
    chunk
    for chunk in chunks
    if len(chunk.page_content) < 50
]

print("Small Chunks:", len(small_chunks))

Small Chunks: 1207

In [44]:
for chunk in small_chunks[:10]:
    print("="*50)
    print(len(chunk.page_content))
    print(repr(chunk.page_content))

==================================================
46
'BPC Initials ___ Sanofi Pasteur Initials ___ 1'
==================================================
46
'BPC Initials ___ Sanofi Pasteur Initials ___ 2'
==================================================
46
'BPC Initials ___ Sanofi Pasteur Initials ___ 3'
==================================================
46
'BPC Initials ___ Sanofi Pasteur Initials ___ 4'
==================================================
32
'Source: AZUL SA, F-1/A, 3/3/2017'
==================================================
32
'Source: AZUL SA, F-1/A, 3/3/2017'
==================================================
32
'Source: AZUL SA, F-1/A, 3/3/2017'
==================================================
32
'Source: AZUL SA, F-1/A, 3/3/2017'
==================================================
32
'Source: AZUL SA, F-1/A, 3/3/2017'
==================================================
32
'Source: AZUL SA, F-1/A, 3/3/2017'

In [45]:
print("Before Cleaning:", len(chunks))

chunks = [
    chunk
    for chunk in chunks
    if len(chunk.page_content.strip()) >= 50
]

print("After Cleaning:", len(chunks))

Before Cleaning: 39025
After Cleaning: 37818

In [46]:
chunk_lengths = [
    len(chunk.page_content)
    for chunk in chunks
]

print("Min:", min(chunk_lengths))
print("Max:", max(chunk_lengths))
print(
    "Average:",
    round(sum(chunk_lengths)/len(chunk_lengths),2)
)

Min: 50
Max: 1000
Average: 786.51

In [47]:
print(chunks[5550].metadata)

{'source': 'EbixInc_20010515_10-Q_EX-10.3_4049767_EX-10.3_Co-Branding Agreement.txt', 'contract_type': 'Marketing Agreement'}

In [48]:
PROJECT_DIR = Path("/content/drive/MyDrive/legal_ai")
METADATA_DIR = PROJECT_DIR / "metadata"
VECTOR_DIR = PROJECT_DIR / "vectorstores"

METADATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

VECTOR_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Project :", PROJECT_DIR)
print("Metadata:", METADATA_DIR)
print("Vectors :", VECTOR_DIR)

Project : /content/drive/MyDrive/legal_ai
Metadata: /content/drive/MyDrive/legal_ai/metadata
Vectors : /content/drive/MyDrive/legal_ai/vectorstores

In [49]:
with open(
    VECTOR_DIR / "chunks.pkl",
    "wb"
) as f:

    pickle.dump(chunks, f)

Embeddings

In [50]:
from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"
)

/tmp/ipykernel_2108/950273920.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

VectorStore FAISS

In [51]:
from langchain_community.vectorstores import FAISS
faiss_db = FAISS.from_documents(
    documents=chunks,
    embedding=embeddings
)

In [52]:
FAISS_DIR = VECTOR_DIR / "legal_faiss"

faiss_db.save_local(
    str(FAISS_DIR)
)

In [53]:
results = faiss_db.similarity_search(
    "What confidentiality obligations exist?",
    k=5
)

for i, doc in enumerate(results, start=1):

    print("="*80)
    print(f"RESULT {i}")

    print("\nSOURCE:")
    print(doc.metadata["source"])

    print("\nTYPE:")
    print(doc.metadata["contract_type"])

    print("\nTEXT:")
    print(doc.page_content[:500])

================================================================================
RESULT 1

SOURCE:
OFGBANCORP_03_28_2007-EX-10.23-OUTSOURCING AGREEMENT.txt

TYPE:
Outsourcing Agreement

TEXT:
prevent unauthorized access to such materials. Each party shall instruct its employees, agents, and contractors (a) of its confidentiality obligations hereunder and (b) not to attempt to circumvent any such security procedures and devices. Each party's obligation under the preceding sentence may be satisfied by the use of its standard form of confidentiality agreement, if the same reasonably accomplishes the purposes here intended. All such Confidential Information shall be distributed only to p
================================================================================
RESULT 2

SOURCE:
TRICITYBANKSHARESCORP_05_15_1998-EX-10-OUTSOURCING AGREEMENT.txt

TYPE:
Outsourcing Agreement

TEXT:
of its confidentiality obligations hereunder and not to attempt to circumvent any such security procedures and devices.  Each party's obligation under the preceding sentence may be satisfied by the use of its standard form of confidentiality agreement, if the same reasonably accomplishes the purposes here intended.  All such Confidential Information shall be distributed only to persons having a need to know such information to perform their duties in conjunction with this Agreement.
================================================================================
RESULT 3

SOURCE:
SightLife Surgical, Inc. - STRATEGIC SALES _ MARKETING AGREEMENT.txt

TYPE:
Strategic Alliance Agreement

TEXT:
EXHIBIT A   Confidentiality Agreement     Page 11 of 11
================================================================================
RESULT 4

SOURCE:
EhaveInc_20190515_20-F_EX-4.44_11678816_EX-4.44_License Agreement_ Reseller Agreement.txt

TYPE:
License Agreement

TEXT:
13. CONFIDENTIALITY (a) Obligation: Each Party acknowledges that all Confidential Information consists of confidential and proprietary information of the disclosing Party. Each Party shall, and shall cause its employees, agents and contractors to hold Confidential Information of the other Party in confidence, and shall use the same degree of care by instruction, agreement or otherwise, to maintain the confidentiality of the other Party's Confidential Information that it uses to maintain the conf
================================================================================
RESULT 5

SOURCE:
SPIENERGYCO,LTD_03_09_2011-EX-99.5-OPERATIONS AND MAINTENANCE AGREEMENT.txt

TYPE:
Maintenance Agreement

TEXT:
ARTICLE 7.  CONFIDENTIAL INFORMATION

7.1 Confidentiality.

BM25 Retriever

In [54]:
from langchain_community.retrievers import BM25Retriever
bm25_retriever = BM25Retriever.from_documents(
    chunks
)

In [55]:
bm25_retriever.k = 5

In [56]:
results = bm25_retriever.invoke(
    "governing law"
)

for i, doc in enumerate(results, start=1):

    print("="*80)

    print(doc.metadata["source"])

    print("\n")

    print(doc.page_content[:400])

================================================================================
Array BioPharma Inc. - LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT.txt


For the avoidance of doubt, the governing law set forth in Section 18.3 shall not apply to determine any procedural issues. In particular, but without in any way restricting the generality of the foregoing, the Parties agree that the procedural rules of the governing law set forth in Section 18.3 shall not apply with respect to document production or other evidentiary issues, except that all privi
================================================================================
ATMOSENERGYCORP_11_22_2002-EX-10.17-TRANSPORTATION SERVICE AGREEMENT.txt


8.2      Applicable Law. This Agreement and the rights and duties of                   Transporter and Shipper hereunder shall be governed by and                   interpreted in accordance with the laws of the State of                   Arkansas, without recourse to the law governing conflict of                   laws.
================================================================================
Principal Life Insurance Company - Broker Dealer Marketing and Servicing Agreement.txt


in which such person solicits applications and be   licensed with and appointed by Issuer to solicit applications for and service Annuity Contracts.      5 . Broker Dealer will use commercially reasonable efforts to train and instruct its Registered   Representatives not to make recommendations to an applicant to purchase an Annuity Contract in the   absence of reasonable grounds to believe that t
================================================================================
INTERNATIONALFASTFOODCORP_04_04_1997-EX-99-FRANCHISE AGREEMENT.txt


19.4  LICENSES, PERMITS, ETC. The Franchisee shall obtain and maintain all licenses and other permits required by the law of the governing bodies where the Franchised  Restaurant  is located and shall comply with all local  governmental requirements  relating  to the  construction,  equipping  and  operation  of the building and the preparation and sale of items in the Franchised Restaurant.


================================================================================
CardlyticsInc_20180112_S-1_EX-10.16_11002987_EX-10.16_Maintenance Agreement1.txt


receivership or similar proceeding, or makes a general assignment for the benefit of its creditors; (c) Supplier either: (i) merges with another entity, (ii) suffers a transfer involving fifty (50%) percent or more of any class of its voting securities or (iii) transfers all, or substantially all, of its assets; (d) in providing services hereunder, Supplier violates any law or regulation governing

Lets compare FAISS and BM25

In [57]:
query = "indemnification"

faiss_results = faiss_db.similarity_search(
    query,
    k=5
)

bm25_results = bm25_retriever.invoke(
    query
)
print("FAISS")

for doc in faiss_results:
    print(doc.metadata["source"])

print("\nBM25")

for doc in bm25_results:
    print(doc.metadata["source"])

FAISS
DRKOOPCOMINC_04_21_1999-EX-10.28-SPONSORSHIP AGREEMENT.txt
NICELTD_06_26_2003-EX-4.5-OUTSOURCING AGREEMENT.txt
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt
NEONSYSTEMSINC_03_01_1999-EX-10.5-DISTRIBUTOR AGREEMENT_New.txt
ALAMOGORDOFINANCIALCORP_12_16_1999-EX-1-AGENCY AGREEMENT.txt

BM25
BERKELEYLIGHTS,INC_06_26_2020-EX-10.12-COLLABORATION AGREEMENT.txt
PHREESIA,INC_05_28_2019-EX-10.18-STRATEGIC ALLIANCE AGREEMENT.txt
FUSIONPHARMACEUTICALSINC_06_05_2020-EX-10.17-Supply Agreement - FUSION.txt
UpjohnInc_20200121_10-12G_EX-2.6_11948692_EX-2.6_Manufacturing Agreement_ Supply Agreement.txt
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt

In [58]:
query = "force majeure"
faiss_results = faiss_db.similarity_search(
    query,
    k=5
)

bm25_results = bm25_retriever.invoke(
    query
)
print("FAISS")

for doc in faiss_results:
    print(doc.metadata["source"])

print("\nBM25")

for doc in bm25_results:
    print(doc.metadata["source"])

FAISS
SANDRIDGEENERGYINC_08_06_2009-EX-10.6-OPERATIONS AND MAINTENANCE AGREEMENT.txt
VERTEXENERGYINC_08_14_2014-EX-10.24-OPERATION AND MAINTENANCE AGREEMENT.txt
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt
ON2TECHNOLOGIES,INC_11_17_2006-EX-10.3-SUPPORT AND MAINTENANCE AGREEMENT.txt
PACIRA PHARMACEUTICALS, INC. - A_R STRATEGIC LICENSING, DISTRIBUTION AND MARKETING AGREEMENT .txt

BM25
PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-99.1_Hosting Agreement.txt
TUNIUCORP_03_06_2014-EX-10-COOPERATION AGREEMENT.txt
BellringBrandsInc_20190920_S-1_EX-10.12_11817081_EX-10.12_Manufacturing Agreement1.txt
BIOCEPTINC_08_19_2013-EX-10-COLLABORATION AGREEMENT.txt
MIDDLEBROOKPHARMACEUTICALS,INC_03_18_2010-EX-10.1-PROMOTION AGREEMENT.txt

In [59]:
for doc in faiss_results:
    print("="*80)
    print(doc.page_content[:500])

================================================================================
17







ARTICLE VII  FORCE MAJEURE

7.1 Procedure.
================================================================================
"Force Majeure" means any cause or causes not reasonably within the control of the Party claiming suspension and which, by the exercise of reasonable diligence, such Party is unable to prevent or overcome, including, without limitation, acts of God, acts, omissions to act, and/or delays in action of federal, state, or local government or any agency thereof, strikes, lockouts, work stoppages, or other industrial disturbances, acts of a public enemy, sabotage, wars, blockades, insurrections, riots
================================================================================
1.32 "Force Majeure" means any circumstances whatsoever which are not within the reasonable control of the Party affected thereby, potentially including an act of God, war, act of terrorism, insurrection, riot, strike or labor dispute, shortage of materials, fire, explosion, flood, earthquake, government requisition or allocation, breakdown of or damage to plant, equipment or facilities, interruption or delay in transportation, fuel supplies or electrical power, embargo, boycott, order or act of
================================================================================
10.2 Force Majeure. Any failure by either Party to perform, to the extent and only for so long as such Party is prevented from performing for one or more of the reasons described herein, any obligation hereunder arising under or in connection with this Agreement shall be excused (to such extent and for such period) if such failure shall have been caused by any act or circumstance beyond the reasonable control of such Party, including, but without limiting the

generality of the foregoing, any Ac
================================================================================
-7-

"Force Majeure"



Means in relation to either Party, any cause affecting the performance of this Agreement or the Supply  Agreement arising from or attributable to any acts, events, non-happenings, omissions or accidents beyond the  reasonable control of the Party to perform and in particular but without limiting the generality thereof shall  include strikes and labor disturbances, lock-outs, industrial action, civil commotion, riot, invasion, war, threat of  or preparation for war, terror

In [60]:
for doc in bm25_results:
    print("="*80)
    print(doc.page_content[:500])

================================================================================
14.2 The Party prevented from fulfilling its obligations shall on becoming aware of such event inform the other Party in writing of such force majeure event as soon as possible. If the affected Party fails to inform the other Party of the occurrence of a force majeure event as set out in article 14.1 above, then such Party thereafter shall not be entitled to refer such events to force majeure as a reason for non-fulfillment. This obligation does not apply if the force majeure event is known by b
================================================================================
The force majeure hereunder shall mean the natural disaster, war, political event, and adjustment of laws, regulations and state policies. If the performance of this Agreement by one Party or the Parties according to provisions agreed hereunder is directly affected by the force majeure event, the affected Party shall immediately notify the other Party or its attorney-in-fact of the situation of the force majeure event, and shall, within fifteen (15) days, provide the detailed information of the
================================================================================
more, the Party not affected shall be entitled to terminate this Agreement by giving notice to take effect immediately. The foregoing shall not relieve either Party of any obligation to make payments required pursuant to this Agreement in accordance with the terms hereof. Notwithstanding the foregoing, in the event there is a force majeure at either Heritage production facility, then the non-force majeure facility shall not be required to produce the total production quantities agreed upon for b
================================================================================
majeure shall be tolled for the duration of such force majeure. In no event shall any party be required to prevent or settle any labor disturbance or dispute. In the event of a force majeure that persists for thirty (30) days or more, then either party may terminate this Agreement upon written notice to the other party.
================================================================================
provided in Section 18 above with  respect to MBRK's right to terminate this Agreement in the event that there is an inability to manufacture MOXATAG  due to force majeure events, should the event(s) of force majeure suffered by a party extend beyond a ninety (90) day period, the other party may then terminate this Agreement by written notice to the non-performing party.

Reciprocal Rank Fusion

In [61]:
from collections import defaultdict

def reciprocal_rank_fusion(results, k=60):

    scores = defaultdict(float)
    doc_map = {}

    for docs in results:

        for rank, doc in enumerate(docs):

            key = (
                doc.metadata["source"],
                doc.page_content[:100]
            )

            scores[key] += 1/(rank+k)

            doc_map[key] = doc

    reranked = sorted(
        scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return [
        doc_map[key]
        for key, score in reranked
    ]

In [62]:
def hybrid_search(query, k=5):

    dense_results = faiss_db.similarity_search(
        query,
        k=k
    )

    sparse_results = bm25_retriever.invoke(
        query
    )

    fused = reciprocal_rank_fusion(
        [
            dense_results,
            sparse_results
        ]
    )

    return fused[:k]

In [63]:
query = "force majeure"

results = hybrid_search(query)

for i, doc in enumerate(results, start=1):

    print("="*100)
    print(f"RESULT {i}")

    print("\nSOURCE:")
    print(doc.metadata["source"])

    print("\nCONTRACT TYPE:")
    print(doc.metadata.get("contract_type", "Unknown"))

    print("\nTEXT:")
    print(doc.page_content[:1000])

====================================================================================================
RESULT 1

SOURCE:
SANDRIDGEENERGYINC_08_06_2009-EX-10.6-OPERATIONS AND MAINTENANCE AGREEMENT.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
17







ARTICLE VII  FORCE MAJEURE

7.1 Procedure.
====================================================================================================
RESULT 2

SOURCE:
PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-99.1_Hosting Agreement.txt

CONTRACT TYPE:
Hosting Agreement

TEXT:
14.2 The Party prevented from fulfilling its obligations shall on becoming aware of such event inform the other Party in writing of such force majeure event as soon as possible. If the affected Party fails to inform the other Party of the occurrence of a force majeure event as set out in article 14.1 above, then such Party thereafter shall not be entitled to refer such events to force majeure as a reason for non-fulfillment. This obligation does not apply if the force majeure event is known by both Parties or the affected Party is unable to inform the other Party due to the force majeure event.
====================================================================================================
RESULT 3

SOURCE:
VERTEXENERGYINC_08_14_2014-EX-10.24-OPERATION AND MAINTENANCE AGREEMENT.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
"Force Majeure" means any cause or causes not reasonably within the control of the Party claiming suspension and which, by the exercise of reasonable diligence, such Party is unable to prevent or overcome, including, without limitation, acts of God, acts, omissions to act, and/or delays in action of federal, state, or local government or any agency thereof, strikes, lockouts, work stoppages, or other industrial disturbances, acts of a public enemy, sabotage, wars, blockades, insurrections, riots, acts of terror, epidemics, landslides, lightning, earthquakes, fires, storms, storm warnings, floods, washouts, extreme cold or freezing weather, arrests and restraints of governments

2 10.23
====================================================================================================
RESULT 4

SOURCE:
TUNIUCORP_03_06_2014-EX-10-COOPERATION AGREEMENT.txt

CONTRACT TYPE:
Cooperation Agreement

TEXT:
The force majeure hereunder shall mean the natural disaster, war, political event, and adjustment of laws, regulations and state policies. If the performance of this Agreement by one Party or the Parties according to provisions agreed hereunder is directly affected by the force majeure event, the affected Party shall immediately notify the other Party or its attorney-in-fact of the situation of the force majeure event, and shall, within fifteen (15) days, provide the detailed information of the force majeure event or the reason for non-performance or partial performance or delay of performance of this Agreement as well as valid evidence thereof (which shall be issued by the notarization authority at the place where the force majeure event occurs). The Parties shall negotiate to decide the performance of this Agreement depending on to what degree the performance of this Agreement is influenced by the force majeure, and decide on whether the affected Party may partially perform or
====================================================================================================
RESULT 5

SOURCE:
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
1.32 "Force Majeure" means any circumstances whatsoever which are not within the reasonable control of the Party affected thereby, potentially including an act of God, war, act of terrorism, insurrection, riot, strike or labor dispute, shortage of materials, fire, explosion, flood, earthquake, government requisition or allocation, breakdown of or damage to plant, equipment or facilities, interruption or delay in transportation, fuel supplies or electrical power, embargo, boycott, order or act of civil or military authority.

In [64]:
test_queries = [
    "governing law",
    "confidentiality",
    "force majeure",
    "indemnification",
    "termination rights",
    "intellectual property"
]

for query in test_queries:

    print("\n")
    print("#"*120)
    print("QUERY:", query)
    print("#"*120)

    results = hybrid_search(query)

    for i, doc in enumerate(results, start=1):

        print("\n" + "="*100)
        print(f"RESULT {i}")

        print("\nSOURCE:")
        print(doc.metadata["source"])

        print("\nCONTRACT TYPE:")
        print(doc.metadata.get("contract_type", "Unknown"))

        print("\nTEXT:")
        print(doc.page_content[:500])

########################################################################################################################
QUERY: governing law
########################################################################################################################

====================================================================================================
RESULT 1

SOURCE:
ChinaRealEstateInformationCorp_20090929_F-1_EX-10.32_4771615_EX-10.32_Content License Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
10.11. Governing Law. This Agreement and any dispute or claim arising out of or in connection with it or its subject matter shall be governed by,  and construed in accordance with, the laws of the People's Republic of China (without regard to its conflicts of laws rules that would mandate the  application of the laws of another jurisdiction).

====================================================================================================
RESULT 2

SOURCE:
Array BioPharma Inc. - LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT.txt

CONTRACT TYPE:
License Agreement

TEXT:
For the avoidance of doubt, the governing law set forth in Section 18.3 shall not apply to determine any procedural issues. In particular, but without in any way restricting the generality of the foregoing, the Parties agree that the procedural rules of the governing law set forth in Section 18.3 shall not apply with respect to document production or other evidentiary issues, except that all privileges restricting disclosure established under such governing law shall apply and may be invoked by

====================================================================================================
RESULT 3

SOURCE:
OTISWORLDWIDECORP_04_03_2020-EX-10.4-INTELLECTUAL PROPERTY AGREEMENT by and among UNITED TECHNOLOGIES CORPORATION, OTIS WORLDWIDE CORPORATION and CARRIER ~1.txt

CONTRACT TYPE:
Intellectual Property Agreement

TEXT:
14





ARTICLE VIII

GOVERNING LAW AND DISPUTE RESOLUTION

====================================================================================================
RESULT 4

SOURCE:
ATMOSENERGYCORP_11_22_2002-EX-10.17-TRANSPORTATION SERVICE AGREEMENT.txt

CONTRACT TYPE:
Transportation Agreement

TEXT:
8.2      Applicable Law. This Agreement and the rights and duties of                   Transporter and Shipper hereunder shall be governed by and                   interpreted in accordance with the laws of the State of                   Arkansas, without recourse to the law governing conflict of                   laws.

====================================================================================================
RESULT 5

SOURCE:
AtnInternationalInc_20191108_10-Q_EX-10.1_11878541_EX-10.1_Maintenance Agreement.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
3.14 Governing Law. The laws of the State of New York (excluding any laws that direct the application of another jurisdiction's law) govern all matters arising out of or relating to this Agreement and all of the transactions it contemplates, including its validity, interpretation, construction, performance, and enforcement.

3.15 Indemnity


########################################################################################################################
QUERY: confidentiality
########################################################################################################################

====================================================================================================
RESULT 1

SOURCE:
SPIENERGYCO,LTD_03_09_2011-EX-99.5-OPERATIONS AND MAINTENANCE AGREEMENT.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
ARTICLE 7.  CONFIDENTIAL INFORMATION

7.1 Confidentiality.

====================================================================================================
RESULT 2

SOURCE:
HarpoonTherapeuticsInc_20200312_10-K_EX-10.18_12051356_EX-10.18_Development Agreement.txt

CONTRACT TYPE:
Development Agreement

TEXT:
6.13 Confidentiality. The receiving Party shall treat all information subject to review under this Article 6 in accordance with the confidentiality provisions of Article 9 and the Parties shall cause the Audit Expert to enter into a reasonably acceptable confidentiality agreement with AbbVie obligating such firm to retain all such financial information in confidence pursuant to such confidentiality agreement.

====================================================================================================
RESULT 3

SOURCE:
FIDELITYNATIONALINFORMATIONSERVICES,INC_08_05_2009-EX-10.3-INTELLECTUAL PROPERTY AGREEMENT.txt

CONTRACT TYPE:
Intellectual Property Agreement

TEXT:
Section 9.2. Confidentiality.

     (a) Each party acknowledges, and shall cause each member of the Group to acknowledge, that it is in possession of significant confidential or proprietary information concerning the business, operations and assets of the members of the other Group.

====================================================================================================
RESULT 4

SOURCE:
TubeMediaCorp_20060310_8-K_EX-10.1_513921_EX-10.1_Affiliate Agreement.txt

CONTRACT TYPE:
Affiliate Agreement

TEXT:
Section 7(d) and the confidentiality provisions of Section 12, and the Auditor shall execute, in advance, a confidentiality agreement that obligates it to maintain the confidentiality of the terms of this Agreement and the information acquired during the course of the audit. Any officer, employee, consultant or agent of Affiliate that has access to an audit report (who shall be limited to those who are members of Affiliate's corporate audit staff and have a specific need to know the contents the

====================================================================================================
RESULT 5

SOURCE:
SightLife Surgical, Inc. - STRATEGIC SALES _ MARKETING AGREEMENT.txt

CONTRACT TYPE:
Strategic Alliance Agreement

TEXT:
EXHIBIT A   Confidentiality Agreement     Page 11 of 11


########################################################################################################################
QUERY: force majeure
########################################################################################################################

====================================================================================================
RESULT 1

SOURCE:
SANDRIDGEENERGYINC_08_06_2009-EX-10.6-OPERATIONS AND MAINTENANCE AGREEMENT.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
17







ARTICLE VII  FORCE MAJEURE

7.1 Procedure.

====================================================================================================
RESULT 2

SOURCE:
PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-99.1_Hosting Agreement.txt

CONTRACT TYPE:
Hosting Agreement

TEXT:
14.2 The Party prevented from fulfilling its obligations shall on becoming aware of such event inform the other Party in writing of such force majeure event as soon as possible. If the affected Party fails to inform the other Party of the occurrence of a force majeure event as set out in article 14.1 above, then such Party thereafter shall not be entitled to refer such events to force majeure as a reason for non-fulfillment. This obligation does not apply if the force majeure event is known by b

====================================================================================================
RESULT 3

SOURCE:
VERTEXENERGYINC_08_14_2014-EX-10.24-OPERATION AND MAINTENANCE AGREEMENT.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
"Force Majeure" means any cause or causes not reasonably within the control of the Party claiming suspension and which, by the exercise of reasonable diligence, such Party is unable to prevent or overcome, including, without limitation, acts of God, acts, omissions to act, and/or delays in action of federal, state, or local government or any agency thereof, strikes, lockouts, work stoppages, or other industrial disturbances, acts of a public enemy, sabotage, wars, blockades, insurrections, riots

====================================================================================================
RESULT 4

SOURCE:
TUNIUCORP_03_06_2014-EX-10-COOPERATION AGREEMENT.txt

CONTRACT TYPE:
Cooperation Agreement

TEXT:
The force majeure hereunder shall mean the natural disaster, war, political event, and adjustment of laws, regulations and state policies. If the performance of this Agreement by one Party or the Parties according to provisions agreed hereunder is directly affected by the force majeure event, the affected Party shall immediately notify the other Party or its attorney-in-fact of the situation of the force majeure event, and shall, within fifteen (15) days, provide the detailed information of the

====================================================================================================
RESULT 5

SOURCE:
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
1.32 "Force Majeure" means any circumstances whatsoever which are not within the reasonable control of the Party affected thereby, potentially including an act of God, war, act of terrorism, insurrection, riot, strike or labor dispute, shortage of materials, fire, explosion, flood, earthquake, government requisition or allocation, breakdown of or damage to plant, equipment or facilities, interruption or delay in transportation, fuel supplies or electrical power, embargo, boycott, order or act of


########################################################################################################################
QUERY: indemnification
########################################################################################################################

====================================================================================================
RESULT 1

SOURCE:
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
the Indemnifying Party may, upon written notice thereof to the Indemnified Party, assume control of the defense of such Claim with counsel reasonably satisfactory to the Indemnified Party. If a Party believes that a Claim presented to it for indemnification is one as to which the Party seeking indemnification is not entitled to indemnification under, as applicable, Section 11.1 or Section 11.2, it shall so notify the Party seeking indemnification.

====================================================================================================
RESULT 2

SOURCE:
DRKOOPCOMINC_04_21_1999-EX-10.28-SPONSORSHIP AGREEMENT.txt

CONTRACT TYPE:
Sponsorship Agreement

TEXT:
ARTICLE VI.                 REPRESENTATIONS AND WARRANTIES; INDEMNIFICATION

====================================================================================================
RESULT 3

SOURCE:
BERKELEYLIGHTS,INC_06_26_2020-EX-10.12-COLLABORATION AGREEMENT.txt

CONTRACT TYPE:
Collaboration Agreement

TEXT:
12.3 Procedure. Any Party seeking indemnification under this Article 12 (Indemnification; Insurance) will promptly notify the indemnifying Party in writing after the Party seeking indemnification has received notice of any Claim. The Party seeking indemnification will reasonably cooperate with the indemnifying Party in the defense of any such Claim at the cost of the indemnifying Party. An indemnifying Party will not be obligated to defend, indemnify and hold harmless the Party seeking indemnifi

====================================================================================================
RESULT 4

SOURCE:
NICELTD_06_26_2003-EX-4.5-OUTSOURCING AGREEMENT.txt

CONTRACT TYPE:
Outsourcing Agreement

TEXT:
12.9. EMPLOYEE AND CONTRACTOR INDEMNIFICATION. Each of the parties agrees           that it will indemnify the other party against any and all claims           hereafter brought or asserted by any person against the other party           relating to any alleged or actual action or omission to act by the           indemnifying party arising from, or in connection with, such person's           status as an employee or independent Contractor of the indemnifying           person or the termination o

====================================================================================================
RESULT 5

SOURCE:
PHREESIA,INC_05_28_2019-EX-10.18-STRATEGIC ALLIANCE AGREEMENT.txt

CONTRACT TYPE:
Strategic Alliance Agreement

TEXT:
costs pursuant to Section 28.9(e). In addition, the limitations in Section 23.1(b) will not apply (1) to Company's indemnification obligations under Section 22.1(a) or (2) Allscripts indemnification obligations under Section 22.3(a), unless the Company's or Allscripts' indemnification obligation under Section 22.1(a) or 22.3(a), as the case may be, relates to the losses and obligations described in subclauses (a) through (f) of the preceding sentence. [***].


########################################################################################################################
QUERY: termination rights
########################################################################################################################

====================================================================================================
RESULT 1

SOURCE:
BloomEnergyCorp_20180321_DRSA (on S-1)_EX-10_11240356_EX-10_Maintenance Agreement.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
(e) Preservation of Rights. Termination of this Agreement shall not affect any rights or obligations as between the Parties which may have accrued prior to such termination or which expressly or by implication are intended to survive termination whether resulting from the event giving rise to termination or otherwise.

====================================================================================================
RESULT 2

SOURCE:
GlobalTechnologiesGroupInc_20050928_10KSB_EX-10.9_4148808_EX-10.9_Content License Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
7. TERMINATION

7.1 General Termination Rights. Either party may terminate the Agreement at any time in the event of a material breach by the other party that remains uncured after thirty (30) days written notice of the breach.

====================================================================================================
RESULT 3

SOURCE:
CytodynInc_20200109_10-Q_EX-10.5_11941634_EX-10.5_License Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
11.7 Effects of Termination. All of the following effects of termination are in addition to the other rights and remedies that may be available to either of the Parties under this Agreement and shall not be construed to limit any such rights or remedies. In the event of termination of this Agreement by either Party: (a) Without limiting the effect that such termination shall have on any provisions of this Agreement, other than those provisions that this Agreement expressly provides shall survive

====================================================================================================
RESULT 4

SOURCE:
HEALTHGATEDATACORP_11_24_1999-EX-10.1-HOSTING AND MANAGEMENT AGREEMENT (1).txt

CONTRACT TYPE:
Development Agreement

TEXT:
32.4. the following Clauses shall survive termination for whatever cause             of this Agreement: Clauses 4.2, 5, 10.2, 20.4, 23.2, 25-28, 30-34             inclusive.

33.   Rights Upon Termination

      Upon termination of this Agreement and for a period of six (6) months       thereafter, the Publishers will have the following rights and obligations:

====================================================================================================
RESULT 5

SOURCE:
PHREESIA,INC_05_28_2019-EX-10.18-STRATEGIC ALLIANCE AGREEMENT.txt

CONTRACT TYPE:
Strategic Alliance Agreement

TEXT:
will survive and continue after the expiration or termination of this Agreement for the full duration of any Customer Agreement. In addition, the rights and obligations of any Party which, by their nature, extend beyond the expiration or termination of this Agreement will continue in full force and effect notwithstanding the termination of this Agreement. 30


########################################################################################################################
QUERY: intellectual property
########################################################################################################################

====================================================================================================
RESULT 1

SOURCE:
ON2TECHNOLOGIES,INC_11_17_2006-EX-10.3-SUPPORT AND MAINTENANCE AGREEMENT.txt

CONTRACT TYPE:
Maintenance Agreement

TEXT:
ARTICLE VII

                          INTELLECTUAL PROPERTY RIGHTS

====================================================================================================
RESULT 2

SOURCE:
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt

CONTRACT TYPE:
License Agreement

TEXT:
property licensed to such other Party and all embodiments of such intellectual property, which, if not already in such other Party's possession, shall be promptly delivered to it (x) upon any such commencement of a bankruptcy proceeding upon such other Party's written request therefore, unless the Bankrupt Party elects to continue to perform all of its obligations under this Agreement or (y) if not delivered under clause (x), following the rejection of this Agreement by the Bankrupt Party upon w

====================================================================================================
RESULT 3

SOURCE:
BABCOCK_WILCOXENTERPRISES,INC_08_04_2015-EX-10.17-INTELLECTUAL PROPERTY AGREEMENT between THE BABCOCK _ WILCOX COMPANY and BABCOCK _ WILCOX ENTERPRISES, INC..txt

CONTRACT TYPE:
Intellectual Property Agreement

TEXT:
"Intellectual Property" means the rights associated with or arising out of any of the following in any jurisdiction throughout the world: (i) all patents and patent applications, together with all reissuances, divisionals, continuations, continuations-in-part, revisions, renewals, extensions, and reexaminations thereof, and any identified invention disclosures ("Patents"); (ii) trade secret rights and corresponding rights in confidential information and other non-public information (whether or n

====================================================================================================
RESULT 4

SOURCE:
OASYSMOBILE,INC_07_05_2001-EX-10.17-OUTSOURCING AGREEMENT.txt

CONTRACT TYPE:
Outsourcing Agreement

TEXT:
pre-existing HSNS intellectual property or intellectual property developed by HSNS without reference to E.piphany Confidential Information. All data created by HSNS using the Outsourcing Application shall be owned by HSNS.

====================================================================================================
RESULT 5

SOURCE:
ZEBRATECHNOLOGIESCORP_04_16_2014-EX-10.1-INTELLECTUAL PROPERTY AGREEMENT.txt

CONTRACT TYPE:
Intellectual Property Agreement

TEXT:
(kk) "Intellectual Property" means any and all of the following in any jurisdiction throughout the world: (i) patents, patent applications, industrial design rights (including utility model rights, design rights, and industrial property rights), registrations and applications for registration of industrial design rights, patents of importation/confirmation, statutory invention registrations, and certificates of invention and like statutory right, all counterparts, continuations, divisions, conti

In [65]:
test_query = "force majeure"

faiss_results = faiss_db.similarity_search(
    test_query,
    k=5
)

bm25_results = bm25_retriever.invoke(
    test_query
)

hybrid_results = hybrid_search(
    test_query,
    k=5
)

print("\nFAISS")
for doc in faiss_results:
    print(doc.metadata["source"])

print("\nBM25")
for doc in bm25_results:
    print(doc.metadata["source"])

print("\nHYBRID")
for doc in hybrid_results:
    print(doc.metadata["source"])

FAISS
SANDRIDGEENERGYINC_08_06_2009-EX-10.6-OPERATIONS AND MAINTENANCE AGREEMENT.txt
VERTEXENERGYINC_08_14_2014-EX-10.24-OPERATION AND MAINTENANCE AGREEMENT.txt
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt
ON2TECHNOLOGIES,INC_11_17_2006-EX-10.3-SUPPORT AND MAINTENANCE AGREEMENT.txt
PACIRA PHARMACEUTICALS, INC. - A_R STRATEGIC LICENSING, DISTRIBUTION AND MARKETING AGREEMENT .txt

BM25
PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-99.1_Hosting Agreement.txt
TUNIUCORP_03_06_2014-EX-10-COOPERATION AGREEMENT.txt
BellringBrandsInc_20190920_S-1_EX-10.12_11817081_EX-10.12_Manufacturing Agreement1.txt
BIOCEPTINC_08_19_2013-EX-10-COLLABORATION AGREEMENT.txt
MIDDLEBROOKPHARMACEUTICALS,INC_03_18_2010-EX-10.1-PROMOTION AGREEMENT.txt

HYBRID
SANDRIDGEENERGYINC_08_06_2009-EX-10.6-OPERATIONS AND MAINTENANCE AGREEMENT.txt
PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-99.1_Hosting Agreement.txt
VERTEXENERGYINC_08_14_2014-EX-10.24-OPERATION AND MAINTENANCE AGREEMENT.txt
TUNIUCORP_03_06_2014-EX-10-COOPERATION AGREEMENT.txt
AimmuneTherapeuticsInc_20200205_8-K_EX-10.3_11967170_EX-10.3_Development Agreement.txt

In [66]:
with open(
    VECTOR_DIR / "bm25.pkl",
    "wb"
) as f:

    pickle.dump(
        bm25_retriever,
        f
    )

print("BM25 Saved")

BM25 Saved